### ISSUE TITLE
Docker pipeline keeps the `v` in the docker tag for root services

### ISSUE THREAD

**Issue by FlixCoder** [famedly/backend-build-workflows#10]
The docker pipeline for subfolders (correctly) removes the `v` from the version to tag the docker tag: https://github.com/famedly/backend-build-workflows/blob/main/.github/workflows/docker-backend.yml#L77

However, the root service pipeline does not: https://github.com/famedly/backend-build-workflows/blob/main/.github/workflows/docker-backend.yml#L60

We should fix that.

**Comment by jdreichmann** [comment]
Note to this: in the past and in other teams (frontend), everything followed/follows this format. If we do change this, it should be a coordinated effort, as all ansible roles currently also assume this structure. So i'd personally like for this to be discussed with infra and frontend before any larger moves are made to avoid needing to change half of the ansible roles f.ex. or ending up with a split on wether the 'v' is there or not

**Comment by FlixCoder** [comment]
Yep, mostly happened out of a bug, but should be discussed. It is a one character change if we want to keep the v though, even easier.

**Comment by FlixCoder** [comment]
I guess https://www.notion.so/famedly/Nexus-Registry-55dfc4abe7ef4a8ea03946d655238b5d?pvs=4#0f8d8a38a3e04da8b9a93a23f59d683e rather means doing the other way @kate-shine ^^

**Comment by kate-shine** [comment]
Okiii
