### ISSUE TITLE
Docker pipeline can currently not publish docker images for branch names

### ISSUE THREAD

**Issue by FlixCoder** [famedly/backend-build-workflows#9]
In the workflow engine repository, we use `main` of e.g. fhiroxide to pull docker images to the development/test environment. This is currently not possible.

Do we want to switch to using tags only or do we want to push branches? I think pushing branches would be valuable for identifying bugs and testing changes when developing both fhiroxide and the WFE. So I would say we should push branch names as docker image tags, too.

**Comment by emgrav** [comment]
Agreed, we may not want to push every branch automatically but I think it should definitely be possible.
